#!/usr/bin/bash
#//Script Kiddies//
kiddies='\e[1;31m'
kiddes='\e[1;33m'
clear
echo ""
figlet " INSTAGRAM" | lolcat
echo -e $kiddes "#####################"
echo "  # UNTUK Instagram # " | lolcat
echo "  # Penyusun IAM # " | lolcat
echo -e $kiddes "#####################"
echo -e $kiddies"=======================================" 
echo " [1] INSTABOT"  | lolcat
echo " [2] INSTAHACK" | lolcat
echo -e $kiddies"======================================="
read -p " [Insta No]> " insta;

if [ $insta = 1 ] || [ $insta = 1 ]
then
echo "================================================"
python2 instabot.py;
fi

if [ $insta = 2 ] || [ $insta = 2 ]
then
echo "================================================"
python2 instahack.py;
fi
